### ISSUE TITLE
Sourcenext Compatibility 

### ISSUE THREAD

**Issue by HimoriK** [OpenBiohazard2/OpenBiohazard2#6]
Is Sourcenext usable with this? The project wouldn't build with it's data.

It does however, boot on the original JS code.

**Comment by samuelyuan** [comment]
Sourcenext should work with this project. Can you check the GAME_REGION variable in game/resource.go is set appropriately?

**Comment by HimoriK** [comment]
Some files show as JP, I changed the .bin files to direct paths and the game started, will check more later.

**Comment by HimoriK** [comment]
Tested further, crashes after entering 'original mode' 
![image](https://user-images.githubusercontent.com/93024680/235380381-69b1adcf-3e22-426a-aeee-afa60bd1d58e.png)

I assume it can't load/find the models and room properties, do you use discord?
I left the GAME_REGION blank since my files didn't seem associated with any regions in the script.
It's likely not loading the correct data to start the game.

**Comment by samuelyuan** [comment]
GAME_REGION is supposed to be set to a value because it's not fixed. In your directory, you can check the folder `OpenBiohazard2\data\PL0` and check whether there is a RDP folder or RDU folder. If the folder is RDP, set GAME_REGION = "P". If the folder is RDU, set GAME_REGION = "U".

**Comment by samuelyuan** [comment]
I made a change to validate whether the game folders exist. Can you download the latest version of the project and rebuild to confirm all the game folders exist? If there are any issues, you should get a clear error message.

**Comment by HimoriK** [comment]
![image](https://github.com/OpenBiohazard2/OpenBiohazard2/assets/93024680/445f9ec2-a7bc-49b6-9007-e47100f5c76c)
This is what shows in my PL0 folder. I have no such RDP or RDU folder, only 'Rdt'. My game doesn't build unless I point the INVENTORY_FILE to 'st0_jp.tim', and I think we might have different game data files or they are named differently. I'm using the 'english' mod of sourcenext. Also your latest commit doesn't have GAME_REGION in it. Might I suggest sharing your files or showing your folder structure? Update: I pointed RDT_FOLDER to 'Rdt' and the game loaded with Leon, thanks. Out of curiosity, what does the 't' stand for?

**Comment by samuelyuan** [comment]
I removed GAME_REGION in the latest commit to simplify the logic. The file validation can be improved to catch these errors much more quickly.

I'm not sure why your RDT folder is called "RDT". It could be because the file extension for the rooms is .RDT, but I had only seen RDP or RDU before.
