### ISSUE TITLE
Ignore upper/lower case data files

### ISSUE THREAD

**Issue by elmarsan** [OpenBiohazard2/OpenBiohazard2#7]
My version of Resident Evil 2 has all source files in lowercase.

So I'm getting errors like this: `ESP file doesn't exist: data/Common/DATP/CORE00.ESP` 
I've actually got the file, but mine is: `OpenBiohazard2/data/common/datp/core00.esp`

**Comment by samuelyuan** [comment]
I made a code change to check whether the game folders exist. If the folder doesn't exist, the game will throw an exception. Can you confirm the data files are in the correct directory and all the folders exist?

**Comment by elmarsan** [comment]
It seems to be working but the message is not very helpful:

```
Validating game folders exist...
Folder data/ exists and has 11 files
2023/05/16 23:23:21 Missing data error: Unable to find folder: data/Common/. Error: <nil>
```

I'm open to add some logic for reading game data in base of different regions in order to avoid upper/lower case problems.
Let me know if you would like to have this feature.

**Comment by samuelyuan** [comment]
The file loading didn't work because you should have seen the message "Validated game folders exist". In your case, the game isn't able to find the "Common" folder under your data directory. What does the file structure look like on your local machine?

When I run the game, this is the output for the file validation:
```
Validating game folders exist...
Folder data/ exists and has 6 files
Folder data/Common/ exists and has 5 files
Folder data/Common/bin/ exists and has 9 files
Folder data/Common/Door/ exists and has 56 files
Folder data/Pl0/ exists and has 5 files
Folder data/Pl0/RDP/ exists and has 250 files
Folder data/Common/DATP/ exists and has 104 files
Validated game folders exist
```

The topmost level should be "data" and the "Common" folder should be under "data". When I run it on Windows, I was still able to load all the files regardless of whether COMMON_FOLDER is uppercase or lowercase. If you are sure your file directory is correct and the problem is a case issue, you can manually change COMMON_FOLDER in resource.go to match your folder name and rebuild.

**Comment by elmarsan** [comment]
I've been able to make it works. But it's not enough just by changing `COMMON_FOLDER`.
BTW I'm on Linux.

This is the output:
```
Validating game folders exist...
Folder data/ exists and has 11 files
Folder data/common/ exists and has 5 files
Folder data/common/bin/ exists and has 9 files
Folder data/common/door/ exists and has 56 files
Folder data/pl0/ exists and has 5 files
Folder data/pl0/rdp/ exists and has 250 files
Folder data/common/datp/ exists and has 104 files
Validated game folders exist
```

I had to replace all leading uppercase by lowecase in `resource.go`, it now looks:

```go
const (
        BASE_FOLDER         = "data/"
        COMMON_FOLDER       = BASE_FOLDER + "common/"
        COMMON_BIN_FOLDER   = COMMON_FOLDER + "bin/"
        ROOMCUT_FILE        = COMMON_BIN_FOLDER + "roomcut.bin"
        ITEMDATA_FILE       = COMMON_BIN_FOLDER + "itemdata.bin"
        ESPDATA1_FILE       = COMMON_BIN_FOLDER + "espdat1.bin"
        ESPDATA2_FILE       = COMMON_BIN_FOLDER + "espdat2.bin"
        COMMON_DOOR_FOLDER  = COMMON_FOLDER + "door/"
        DOOR_FILE           = COMMON_DOOR_FOLDER + "door%02x.do2"
        PL_FOLDER           = BASE_FOLDER + "pl0/"
        LEON_MODEL_FILE     = PL_FOLDER + "pld/pl00.pld"
        ENEMY_FILE          = PL_FOLDER + "emd0/em%03x.emd"
        RDT_FOLDER          = PL_FOLDER + "rdp/"
        RDT_FILE            = RDT_FOLDER + "room%01d%02x%01d.rdt"
        COMMON_DATA_FOLDER  = COMMON_FOLDER + "datp/"
        CORE_SPRITE_FILE    = COMMON_DATA_FOLDER + "core00.esp"
        INVENTORY_FILE      = COMMON_DATA_FOLDER + "st0_pl.tim"
        MENU_IMAGE_FILE     = COMMON_DATA_FOLDER + "Tit_bg.adt"
        MENU_TEXT_FILE      = COMMON_DATA_FOLDER + "tmojipal.bin"
        ITEMALL_FILE        = COMMON_DATA_FOLDER + "itemall.bin"
        SAVE_SCREEN_FILE    = COMMON_DATA_FOLDER + "type00.adt"
        COMMON_SOUND_FOLDER = BASE_FOLDER + "common/sound/"
)
```

**Comment by samuelyuan** [comment]
The issue seems to show up if the filesystem is case-sensitive. I thought the issue was related to the file structure because another person reported a similar issue with loading the files.

**Comment by elmarsan** [comment]
It makes sense, would you like have some control over this? 
I can work on that.

**Comment by samuelyuan** [comment]
If you are interested, you can make improvements.
